travel_mate/src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class, inversedBy="cities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $countryCode;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="city")
     */
    private $events;

    public function __construct()
    {
        // $this->event = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCountry(): ?Country
    {
        return $this->Country;
    }

    public function setCountry(?Country $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    public function setCountryCode(?string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setCity($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->removeElement($event)) {
            // set the owning side to null (unless already changed)
            if ($event->getCity() === $this) {
                $event->setCity(null);
            }
        }

        return $this;
    }
}

travel_mate/templates/partials/_category-nav.html.twig
    <nav class="category-nav">
        <div class="category-nav__items">
            <a href="{{ path("category_index") }}">Derniers ajouts</a>
            {% for category in categories %}
                <a href="{{ path("category_show", {id:category.id}) }}">{{ category.name }}</a>
            {% endfor %}
        </div>
    </nav>

travel_mate/templates/partials/_flash.html.twig
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="alert alert-{{ label }} flash ">
            {{ message }}
        </div>
    {% endfor %}
{% endfor %}

travel_mate/templates/partials/_nav.html.twig
<header>
    <nav class="nav">
        <div class="nav__items">
            <h1>Travel Mate</h1>
            <a href="{{ path('home_index') }}">home</a>
            <a href="">destination</a>
            <a href="{{ path('category_index') }}">categories</a>
        </div>
        {% if is_granted('ROLE_ADMIN') %}
            admin - <a href="{{path('backoffice_home')}}">Backoffice</a>
        {% elseif is_granted('ROLE_USER') %}
            User
        {% else %}
            no connected
        {% endif %}
        {% if app.user %}
          <div class="connected">
            <p><strong><bold>{{ app.user.email }}</bold></strong></p>
            <div class="nav__account">
                <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle account-button" data-bs-toggle="dropdown" aria-expanded="false">
                    Account
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><button class="dropdown-item" type="button"><a href="{{ path('backoffice_home') }}">Backoffice</a></button></li>
                    <li><button class="dropdown-item deconnexion-button" type="button"><a class="text-decoration-none" href="{{ path('app_logout') }}">se déconnecter</a></button></li>
                </ul>
                </div>
            </div>
          </div>
        {% else %}
            <button type="button" class="btn btn-outline-success">
              <a class="text-decoration-none" href="{{ path('app_login') }}">Se connecter</a>
            </button>
        {% endif %}
        
    </nav>

    <script type="text/javascript">
        window.addEventListener("scroll", function() {
            var header = document.querySelector(".nav");
            header.classList.toggle("sticky", window.scrollY > 0)
        })
    </script>
</header>
<section id="content">

travel_mate/templates/partials/_search-nav.html.twig
    <nav class="search-nav">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            {{ form_row(form.name, {'label': 'foo'}) }}
            {{ form_row(form.category, {'label': 'foo'}) }}
            {{ form_row(form.country, {'label': 'foo'}) }}
            {{ form_row(form.city, {'label': 'foo'}) }}
            {{ form_row(form.date, {'label': 'foo'}) }}
            

            <button type='submit' formnovalidate class="btn btn-light form__submit">Rechercher</button>
        {{ form_end(form) }}
    </nav>